### ISSUE TITLE
Issues with BB10 download

### ISSUE THREAD

**Issue by mattgrande** [gaqzi/phonegap-bb10-file-transfer-test#1]
Hi there, I hope you don't mind me trying to contact you like this...

I came across your example on the BB support forums, and I wasn't able to get it working either... The file downloads, but it seemingly can't be used... Were you ever able to get it working?

Thanks,
-matt.

**Comment by gaqzi** [comment]
No, I never got it working before I had to release the app. And afterwards the BB implementation kinda got forgotten because it's a platform no one really care about here. :x

I would assume that the updates to the cordova API should've taken care of it, but I guess not in that case.

Best of luck!

**Comment by mattgrande** [comment]
Thanks... I'll make sure I'm on the latest cordova / phonegap (although I'm pretty sure we already are), hopefully that helps...
